---
abstract: 'comprehensively parse boolean response strings'
author:
  - 'Mike Doherty <doherty@cs.dal.ca>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Boolean
requires:
  Carp: 0
  Exporter: 0
  Module::Pluggable: 0
  boolean: 0.21
  perl: 5.0100
  utf8: 0
resources:
  bugtracker: http://github.com/doherty/Lingua-Boolean/issues
  repository: http://github.com/doherty/Lingua-Boolean
version: 0.001
