---
abstract: 'comprehensively parse boolean response strings'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Builder: 0.94
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Boolean
requires:
  Carp: 0
  Exporter: 0
  Module::Pluggable: 0
  String::Trim: 0
  boolean: 0.21
  perl: 5.010001
  utf8: 0
resources:
  bugtracker: https://github.com/doherty/Lingua-Boolean/issues
  repository: git://github.com/doherty/Lingua-Boolean.git
version: 0.006
